// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");

var _ABSOLUTE_PATH = Path.resolve("./test", "./");

function toBuffer(value) {
  var array = new Uint32Array(1);
  array[0] = value;
  return array.buffer;
}

function fromBuffer(buffer) {
  var array = new Uint32Array(buffer);
  return array[0];
}

var InputTransfer = {
  toBuffer: toBuffer,
  fromBuffer: fromBuffer
};

function toBuffer$1(value) {
  var array = new Uint32Array(1);
  array[0] = value;
  return array.buffer;
}

function fromBuffer$1(buffer) {
  var array = new Uint32Array(buffer);
  return array[0];
}

var ResultTransfer = {
  toBuffer: toBuffer$1,
  fromBuffer: fromBuffer$1
};

function compute(input) {
  var timeStart = Date.now();
  var array = new Uint8Array(input);
  var array2 = new Uint8Array(input);
  var result = 0;
  for(var i = 0; i < input; ++i){
    for(var j = 0; j < input; ++j){
      result = Math.imul(array[i], array2[j]);
    }
  }
  var timeEnd = Date.now();
  return timeEnd - timeStart | 0;
}

var Nodejs;

var _MODULE_NAME = "TestMngUtils__Thread__Compute__Matrix";

exports.Nodejs = Nodejs;
exports._ABSOLUTE_PATH = _ABSOLUTE_PATH;
exports._MODULE_NAME = _MODULE_NAME;
exports.InputTransfer = InputTransfer;
exports.ResultTransfer = ResultTransfer;
exports.compute = compute;
/* _ABSOLUTE_PATH Not a pure module */
