// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Caml_splice_call = require("rescript/lib/js/caml_splice_call.js");

var _ABSOLUTE_PATH = Path.resolve("./test", "./");

function compute(input) {
  return String(input);
}

function toBuffer(value) {
  var array = new Uint32Array(1);
  array[0] = value;
  return array.buffer;
}

function fromBuffer(buffer) {
  return new Uint32Array(buffer)[0];
}

var InputTransfer = {
  toBuffer: toBuffer,
  fromBuffer: fromBuffer
};

function toBuffer$1(value) {
  var array = new Uint32Array(value.length);
  for(var i = 0 ,i_finish = value.length; i < i_finish; ++i){
    var code = value.codePointAt(i);
    array[i] = code;
  }
  return array.buffer;
}

function fromBuffer$1(buffer) {
  var array = new Uint32Array(buffer);
  var codes = [];
  array.forEach(function (item) {
        codes.push(item);
      });
  return Caml_splice_call.spliceApply(String.fromCharCode, [codes]);
}

var ResultTransfer = {
  toBuffer: toBuffer$1,
  fromBuffer: fromBuffer$1
};

var Nodejs;

var _MODULE_NAME = "TestMngUtils__Thread__Compute";

exports.Nodejs = Nodejs;
exports._ABSOLUTE_PATH = _ABSOLUTE_PATH;
exports._MODULE_NAME = _MODULE_NAME;
exports.compute = compute;
exports.InputTransfer = InputTransfer;
exports.ResultTransfer = ResultTransfer;
/* _ABSOLUTE_PATH Not a pure module */
