// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var MngUtils__Async = require("../src/MngUtils__Async.bs.js");
var MngUtils__AsyncRunner = require("../src/MngUtils__AsyncRunner.bs.js");

Test.testAsync("AsyncRunner", 30000, (function (cb) {
        var runner = MngUtils__AsyncRunner.make([
              (function (param) {
                  return MngUtils__Async.sleep(1000).then(function (param) {
                              return Promise.resolve(1);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(2000).then(function (param) {
                              return Promise.resolve(2);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(2000).then(function (param) {
                              return Promise.resolve(3);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(2000).then(function (param) {
                              return Promise.resolve(4);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(3000).then(function (param) {
                              return Promise.resolve(5);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(4000).then(function (param) {
                              return Promise.resolve(6);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(3000).then(function (param) {
                              return Promise.resolve(7);
                            });
                }),
              (function (param) {
                  return MngUtils__Async.sleep(4000).then(function (param) {
                              return Promise.resolve(8);
                            });
                })
            ], 4);
        MngUtils__AsyncRunner.runWithPollTimeWithTimeout(runner, 150, undefined).then(function (results) {
              console.log("results: ", results);
              Curry._2(cb, 0, undefined);
              return Promise.resolve(undefined);
            });
      }));

/*  Not a pure module */
