// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Test = require("rescript-test/src/Test.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var Promises = require("fs/promises");

Test.testAsync("readFile", 30000, (function (cb) {
        Promises.readFile("./src/MngUtils__Nodejs.res", {
                encoding: "utf-8"
              }).then(function (contents) {
              console.log("contents:\n", contents);
              Curry._2(cb, 0, undefined);
              return Promise.resolve(undefined);
            });
        
      }));

/*  Not a pure module */
