// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");

function fileSize(path) {
  return new Promise((function (resolve, reject) {
                Fs.stat(path, (function (error, stats) {
                        if (error == null) {
                          return resolve(stats.size);
                        } else {
                          return reject(error);
                        }
                      }));
                
              }));
}

var Fs$1 = {
  fileSize: fileSize
};

var Dirent = {};

var Stats = {};

exports.Fs = Fs$1;
exports.Dirent = Dirent;
exports.Stats = Stats;
/* fs Not a pure module */
